# Generated by Django 3.1.7 on 2021-02-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applikacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Applikáció',
                'verbose_name_plural': 'Applikációk',
            },
        ),
    ]
